---
nginx_conf: nginx.conf.j2
nginx_path: /etc/nginx
nginx_logs_root: /var/log/nginx
nginx_user: www-data
nginx_fastcgi_buffers: 8 8k
nginx_fastcgi_buffer_size: 8k
nginx_sites_confs:
  - src: no-default.conf.j2

# Fastcgi cache params
nginx_cache_path: /var/cache/nginx
nginx_cache_key_storage_size: 10m
nginx_cache_size: 250m
nginx_cache_inactive: 1h
