# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: jjz;%=7^W+\Wecsy

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: KWekkkX6YjDVAJ3j
    salt: "79rv4D65N2nQcvGL"

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  fiipregatit.civictech.ro:
    env:
      db_password: Jn29bxjD5rYPsmUQ
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "xS=ARb4eVq_;{O%1RnQycS<adm:.txx-VlmAsF}/?k$afXn}:y0]As`C==_Qm{:y"
      secure_auth_key: "(HlnKzW{8E{+?90|uig$NIo!l*xAWr|zJw[h.c^j:J>roQgi):8w/|E[vFmIs8?X"
      logged_in_key: "QtetC?!9P#?bB,hQ^(F[k?.P[j^EV@u,sU?%j!T&@w2F[JQizQAcT^l%#t&rkYG("
      nonce_key: "F,O-EBr{}iwlM!^0.mcZASjnqbnE7mhI$.CDen+>HvjI^;5*b1(q6}Gl+#jj}3K|"
      auth_salt: "}PB.p<rn#Z32!3(i:tnVqC@@fW:W/F)a(f^Ih!wMLauE9r3&>%|5pXh0cy:U[_=-"
      secure_auth_salt: "6vLJOWZd_4:7[tJ!I_3$*dX*Ivb7C#<)czy<l?cu?3k/),&jU7bRP>xKa9d4^jzF"
      logged_in_salt: "<lOiS6/`3Gb6>[c<4Ab?]2(hq++#ix8jZGf[)Z66Da/coS-Oz]2jGFRUx!@R1m]i"
      nonce_salt: "<?nxof!-#AGN]7]#%d6X#vcM)s/O;;vyZX]9Da=uu#9Wu*-M<G6A/,7A>[I,(@dA"
      #  fiipregatit.claudiuceia.ro:
      #env:
      #db_password: Jn29bxjD5rYPsmUQ
      # Generate your keys here: https://roots.io/salts.html
      #auth_key: "xS=ARb4eVq_;{O%1RnQycS<adm:.txx-VlmAsF}/?k$afXn}:y0]As`C==_Qm{:y"
      #secure_auth_key: "(HlnKzW{8E{+?90|uig$NIo!l*xAWr|zJw[h.c^j:J>roQgi):8w/|E[vFmIs8?X"
      #logged_in_key: "QtetC?!9P#?bB,hQ^(F[k?.P[j^EV@u,sU?%j!T&@w2F[JQizQAcT^l%#t&rkYG("
      #nonce_key: "F,O-EBr{}iwlM!^0.mcZASjnqbnE7mhI$.CDen+>HvjI^;5*b1(q6}Gl+#jj}3K|"
      #auth_salt: "}PB.p<rn#Z32!3(i:tnVqC@@fW:W/F)a(f^Ih!wMLauE9r3&>%|5pXh0cy:U[_=-"
      #secure_auth_salt: "6vLJOWZd_4:7[tJ!I_3$*dX*Ivb7C#<)czy<l?cu?3k/),&jU7bRP>xKa9d4^jzF"
      #logged_in_salt: "<lOiS6/`3Gb6>[c<4Ab?]2(hq++#ix8jZGf[)Z66Da/coS-Oz]2jGFRUx!@R1m]i"
      #nonce_salt: "<?nxof!-#AGN]7]#%d6X#vcM)s/O;;vyZX]9Da=uu#9Wu*-M<G6A/,7A>[I,(@dA"

