---
- name: disable temporary challenge sites
  include: disable_challenge_sites.yml

- name: restart memcached
  service:
    name: memcached
    state: restarted

- name: reload php-fpm
  service:
    name: php7.1-fpm
    state: reloaded

- include: reload_nginx.yml
