---
- name: Install ssmtp
  apt:
    name: ssmtp
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_cache_valid_time }}"

- name: ssmtp configuration
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
