---
- block:
  - name: Warn about updating network database.
    debug:
      msg: "Updating the network database could take a long time with a large number of sites."
    when: project.update_db_on_deploy | default(update_db_on_deploy) and project.multisite.enabled | default(false)

  - name: Update WP database
    command: wp core update-db {{ project.multisite.enabled | default(false) | ternary('--network', '') }}
    args:
      chdir: "{{ deploy_helper.current_path }}"
    when: project.update_db_on_deploy | default(update_db_on_deploy)

  - name: Get WP theme template and stylesheet roots
    command: wp option get {{ item }} --skip-plugins --skip-themes
    args:
      chdir: "{{ deploy_helper.current_path }}"
    register: wp_template_root
    changed_when: false
    failed_when: wp_template_root.stderr != ""
    with_items:
      - template_root
      - stylesheet_root

  - name: Update WP theme paths
    command: >
      wp option set {{ item.item }}
      {{ item.stdout | regex_replace(deploy_helper.releases_path + '/[^/]+(.*)', deploy_helper.new_release_path + '\1') }}
    args:
      chdir: "{{ deploy_helper.current_path }}"
    when: deploy_helper.releases_path in item.stdout
    with_items: "{{ wp_template_root.results }}"

  when: wp_installed | success

- name: Reload php-fpm
  shell: sudo service php7.1-fpm reload
  args:
    warn: false
