---
- name: Create file with multisite constants defined as false
  copy:
    src: "tmp_multisite_constants.php"
    dest: "{{ deploy_helper.shared_path }}/tmp_multisite_constants.php"

- name: WordPress Installed?
  command: wp core is-installed --skip-plugins --skip-themes --require={{ deploy_helper.shared_path }}/tmp_multisite_constants.php
  args:
    chdir: "{{ deploy_helper.new_release_path }}"
  register: wp_installed
  changed_when: false
  failed_when: wp_installed.stderr != ""
