- name: composer
  src: geerlingguy.composer
  version: 1.5.0

- name: ntp
  src: geerlingguy.ntp
  version: 1.3.0

- name: logrotate
  src: nickhammond.logrotate
  version: e7a498d

- name: swapfile
  src: kamaln7.swapfile
  version: 0.4

- src: geerlingguy.daemonize
  version: 1.1.1

- name: mailhog
  src: geerlingguy.mailhog
  version: 2.1.0

- name: bedrock-site-protect
  src: louim.bedrock-site-protect
  version: 1.2.0
